### ISSUE TITLE
Inconsistent state

### ISSUE THREAD

**Issue by deen13** [SmartsquareGmbH/kickpi#22]
The lobby end up in an inconsistent state today after we finished a 1on1. The lobby was still alive after the tenth goal with a duplicated player.

@rubengees do u know an api to store the logs online? This would be very helpful in this case.

**Comment by rubengees** [comment]
We could use Firebase Crashlytics which if i recall correctly, has the ability to save custom "crashes" once we detect inconsistent state.
We would also get all traditional crashes in a nice UI.
